### ISSUE TITLE
Deactivate Validator country graph filter

### ISSUE THREAD

**Issue by vovanovaque** [chain4travel/camino-public-issues#4] opened 2023-11-08 13:02 UTC
**Component**
Explorer https://suite.camino.network/explorer/camino/validators

**Describe the Bug**
When on this page and clicking on Nodes, the graphic with validators disappears 

**Steps to Reproduce**
Disable the click on Node 
 
**Expected Behavior**
I should not be able to click on Node. 
<img width="1255" alt="before" src="https://github.com/chain4travel/camino-public-issues/assets/108511295/3079afaa-53d3-42b3-a0ba-5ecd579b2bc1">
<img width="1263" alt="after" src="https://github.com/chain4travel/camino-public-issues/assets/108511295/db6c15aa-d36c-4f8f-99e5-384a53252afa">

**Screenshots**
If possible, attach screenshots to help illustrate the issue.

**Logs**
If relevant, include any logs that highlight the problem. By default, the log directory for your node can be found at `~/.caminogo/logs/`.

**Metrics**
If relevant, share any metrics from your node that might help in diagnosing the issue.

**Operating System**
Mention the operating system where the bug was encountered.

**Additional Context**
Provide any other pertinent information or context regarding the problem.

**Comment by Noctunus** [comment] 2024-02-13 13:42
Thanks for the report!
The issue is reproducible and will be addressed in an upcoming suite release.

Devs: Filtering on the legend would make sense if we'd have more than one item in the graph, but in this case we only have one and deactivating the only visible item type will hide everything. We should deactivate the filter functionality here.

**Comment by aeddaqqa** [comment] 2024-03-01 09:33
@mikrub  the changes are ready to review in the dev.suite

**Closed as completed** 2024-03-11 08:43 UTC
Labels: bug, suite
